### ISSUE TITLE
shield not work and sometimes mobs deal more damage in single player

### ISSUE THREAD

**Issue by ItzSidaOk** [Neddslayer/sharedhealth#2]

**Comment by Neddslayer** [comment]
Could you provide more information? How much more damage is "more"? What version are you experiencing this on? What OS are you using?

**Comment by lastneon1** [comment]
I'm having the same problem with shields. 1.20.1, Windows.

**Comment by Neddslayer** [comment]
I am unable to reproduce on the latest version. However, seeing as the 1.20.1 version is the most downloaded, I'll backport the current codebase to 1.20.1.

**Comment by Neddslayer** [comment]
It's on modrinth.

**Comment by lastneon1** [comment]
Hey, thx for backport but when i use the newer version my modpack crashes. It won't happen with version 1.0.0_01

**Comment by Neddslayer** [comment]
Please post the crash logs, mod list, and game version in a _seperate_ issue.
