### ISSUE TITLE
1.21 minecraft version

### ISSUE THREAD

**Issue by Zaneriis** [Neddslayer/sharedhealth#3]
Is it planned to update the mod for 1.21 ?
Thank you :)

**Comment by Neddslayer** [comment]
I'll do it when I get the time, I've been pretty busy with life stuff recently.

**Comment by Zaneriis** [comment]
Thank you for the update ! Very quick 🙏
An other thing, it's not important but on the [modrinth](https://modrinth.com/mod/sharedhealth) page of the mod, the description isn't update 🤭
![image](https://github.com/user-attachments/assets/23bab29a-c0b4-425f-b948-e775a0888c4a)
Thank again !

**Comment by Neddslayer** [comment]
1.19.4+ means 1.19.4 _and above_, not only 1.19.4. There's no issue there.
