### ISSUE TITLE
1.21.3 version please <3

### ISSUE THREAD

**Issue by elybeatmaker** [Neddslayer/sharedhealth#5]
Hello! 
I love your mod! I really don't want to pressure anyone, but I'd love if you could update it whenever you have the time to do it! 
Thank you so much for your work and for your time!

**Comment by Neddslayer** [comment]
Of course! I've been busy with school and other projects, but ideally I should get a build out by today or tomorrow.

**Comment by Neddslayer** [comment]
Just pushed the update to Github, I'll close this and post it on Modrinth. Thank you for your support!
